/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WpslRouteImport } from './routes/wpsl'
import { Route as IndexRouteImport } from './routes/index'

const WpslRoute = WpslRouteImport.update({
  id: '/wpsl',
  path: '/wpsl',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wpsl': typeof WpslRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wpsl': typeof WpslRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wpsl': typeof WpslRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wpsl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wpsl'
  id: '__root__' | '/' | '/wpsl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WpslRoute: typeof WpslRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wpsl': {
      id: '/wpsl'
      path: '/wpsl'
      fullPath: '/wpsl'
      preLoaderRoute: typeof WpslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WpslRoute: WpslRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
